import React from 'react'
import '../style/Content.css'

interface ContentProps {
    value?: string;
}

function Content({ value }: ContentProps) {
    return (
        <div className='content'>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
            <div>React, This is {value} page</div><br/>
      </div>
    )
}

Content.defaultProps = {
    value: 'Page information'
}

export default Content